{
 "title": "RedPill Dashboard",
 "time": { "from": "2025-07-17T10:04:38.000Z", "to": "2025-07-17T10:17:55.000Z" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "station",
    "query": "SELECT DISTINCT ground_station_id FROM packets"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n  <img src=\"/public/imported_images/logomissione1.png\" \n       style=\"width: 3000px; height: auto; border: none;\">\n</div>"
   }
  },
  {
   "title": "Total saved packets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  COUNT(id) as total_packets\nFROM packets",
     "rawQueryText": "SELECT\n  COUNT(id) as total_packets\nFROM packets",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "RSSI and SNR",
   "type": "timeseries",
   "description": "The graph report RSSI and SNR values acquired by the gound station in function of time.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%s', substr(timestamp,1,19)) AS time, -- numero di secondi da 1970\n  rssi AS RSSI,\n  snr AS SNR\nFROM packets\nWHERE ground_station_id = '1'\nORDER BY time",
     "rawQueryText": "SELECT \n  strftime('%s', substr(timestamp,1,19)) AS time, -- numero di secondi da 1970\n  rssi AS RSSI,\n  snr AS SNR\nFROM packets\nWHERE ground_station_id = '$station'\nORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Last packet received UTC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n replace(substr(MAX(timestamp), 1, 19), 'T', ' ') AS last_packet_unix\nFROM packets;",
     "rawQueryText": "SELECT\n replace(substr(MAX(timestamp), 1, 19), 'T', ' ') AS last_packet_unix\nFROM packets;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Current Time UTC",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "queryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= 1752746678000 / 1000 and time < 1752747475000 / 1000",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Last RSSI value",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', substr(timestamp,1,19)) AS time,  -- time in secondi\n  RSSI\nFROM packets\nORDER BY time ASC;",
     "rawQueryText": "SELECT\n  strftime('%s', substr(timestamp,1,19)) AS time,  -- time in secondi\n  RSSI\nFROM packets\nORDER BY time ASC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Last SNR value",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', substr(timestamp,1,19)) AS time,  -- time in secondi\n  SNR\nFROM packets\nORDER BY time ASC;",
     "rawQueryText": "SELECT\n  strftime('%s', substr(timestamp,1,19)) AS time,  -- time in secondi\n  SNR\nFROM packets\nORDER BY time ASC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Frequency offset",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%s', substr(timestamp,1,19)) AS time, -- numero di secondi da 1970\n  freq_offset\nFROM packets\nWHERE ground_station_id = '1'\nORDER BY time",
     "rawQueryText": "SELECT \n  strftime('%s', substr(timestamp,1,19)) AS time, -- numero di secondi da 1970\n  freq_offset\nFROM packets\nWHERE ground_station_id = '$station'\nORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Last TEC value",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', substr(timestamp,1,19)) AS time,  -- time in secondi\n  TEC\nFROM packets\nORDER BY time ASC;",
     "rawQueryText": "SELECT\n  strftime('%s', substr(timestamp,1,19)) AS time,  -- time in secondi\n  TEC\nFROM packets\nORDER BY time ASC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Last frequency offset value",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%s', substr(timestamp,1,19)) AS time,  -- time in secondi\n  freq_offset\nFROM packets\nORDER BY time ASC;",
     "rawQueryText": "SELECT\n  strftime('%s', substr(timestamp,1,19)) AS time,  -- time in secondi\n  freq_offset\nFROM packets\nORDER BY time ASC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "TEC",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 13 },
   "targets": [
    {
     "queryText": "SELECT \n  strftime('%s', substr(timestamp,1,19)) AS time, -- numero di secondi da 1970\n  tec\nFROM packets\nWHERE ground_station_id = '1'\nORDER BY time",
     "rawQueryText": "SELECT \n  strftime('%s', substr(timestamp,1,19)) AS time, -- numero di secondi da 1970\n  tec\nFROM packets\nWHERE ground_station_id = '$station'\nORDER BY time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}